learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
  #Home page.
  path('', views.index, name='index'),
  #Topics page.
  path('topics/', views.topics, name='topics'),
  #Each topic and entries page.
  path('topic/<int:topic_id>/', views.topic, name='topic'),
  #Page to add a new topic.
  path('new_topic/', views.new_topic, name='new_topic'),
  #Page to add a new entry.
  path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
  #Page to edit an entry.
  path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
  # Include default auth urls.
  path('', include('django.contrib.auth.urls')),
  # Page for registration.
  path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
  """A topic user is learning about."""
  text = models.CharField(max_length=200)
  date_added = models.DateTimeField(auto_now_add=True)
  owner = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.text

class Entry(models.Model):
  """ Something specific learned about a topic."""
  topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
  text = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True)

  class Meta:
    verbose_name_plural = 'entries'

  def __str__(self):
    if len(self.text) < 51:
      return self.text
    else: return f'{self.text[:50]}...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
  class Meta:
    model = Topic
    fields = ['text']
    labels = {'text': ''}

class EntryForm(forms.ModelForm):
  class Meta:
    model = Entry
    fields = ['text']
    labels = {'text': 'Entry:'}
    widgets = {'text': forms.Textarea(attrs={'cols': 80})}
    

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def check_topic_owner(topic, request):
  if topic.owner != request.user:
    raise Http404

def index(request):
  """The home page for learning log."""
  return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
  """Show all the topics."""
  topics = Topic.objects.filter(owner=request.user).order_by('date_added')
  context = {'topics': topics}
  return render(request, 'learning_logs/topics.html', context )

@login_required
def topic(request, topic_id):
  """Show a single topic and all its entries."""
  topic = Topic.objects.get(id=topic_id)
  check_topic_owner(topic, request)
  
  entries = topic.entry_set.order_by('-date_added')
  context = {'topic': topic, 'entries': entries}
  return render(request, 'learning_logs/topic.html', context )

@login_required
def new_topic(request):
  """Add a new topic."""
  if request.method != 'POST':
    # No data submitted; create a blank form.
    form = TopicForm()
  else:
    # POST data submitted; process data.
    form = TopicForm(data=request.POST)
    if form.is_valid():
      new_topic = form.save(commit=False)
      new_topic.owner = request.user
      new_topic.save()
      return redirect('learning_logs:topics')
    
  # Display a blank form or invalid form.
  context= {'form': form}
  return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
  """Add a new entry for a particular topic."""
  topic = Topic.objects.get(id=topic_id)

  if request.method != 'POST':
    # No data submitted; create a blank form.
    form = EntryForm()
  else:
    # POST data submitted; process data.
    form = EntryForm(data=request.POST)
    if form.is_valid():
      new_entry = form.save(commit=False)
      new_entry.topic = topic
      check_topic_owner(topic, request)
      new_entry.save()
      return redirect('learning_logs:topic', topic_id=topic_id)

  # Display a blank or invalid form.
  context = {'topic': topic, 'form':form}  
  return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
  """ Edit an existing entry for a particular topic."""
  entry = Entry.objects.get(id=entry_id)
  topic = entry.topic
  check_topic_owner(topic, request)

  if request.method != 'POST':
    # Initial request; pre-fill form with the currnt entry.
    form = EntryForm(instance=entry)
  else:
    # POST data submitted; process data.
    form = EntryForm(instance=entry, data=request.POST)
    if form.is_valid():
      form.save()
      return redirect('learning_logs:topic', topic_id=topic.id)

  # Display a prefilled or invalid form.
  context = {'topic': topic, 'entry':entry, 'form':form}
  return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

def register(request):
  """Register a new user."""
  if request.method != 'POST':
    # Display a blank registration form.
    form = UserCreationForm()
  else:
    # Process a completed form.
    form = UserCreationForm(data=request.POST)
    
    if form.is_valid():
      new_user = form.save()
      #Log the user in and redirect to home page.
      login(request, new_user)
      return redirect('learning_logs:index')
  
  # Display a blank or invalid form.
  context = {'form': form}
  return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0,
    shrink-to-fit=no"/>
  
  <title>Learning Log</title>

  <!-- Optional: Google Font -->
  <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />

  <!--Bootstrap 5 CDN for CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  
  <!--Animate.css CDN for CSS Animations-->
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
      <div class="container-fluid">
        <a href="{% url 'learning_logs:index' %}"><img width='75px' src="{% static 'learning_logs/images/logo.png' %}" alt="my Logo" /></a>
        <a class="d-none d-lg-block navbar-brand text-uppercase fs-4" href="{% url 'learning_logs:index' %}">EduTrack</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link fs-5" aria-current="page" href="{% url 'learning_logs:topics' %}">Topics</a>
            </li>
          </ul>
          <ul class="navbar-nav">
              {% if user.is_authenticated %} 
              <span class='navbar-text fs-5'>Hello, {{user.username}} </span>
            <form class="d-flex" role="logout" action="{% url 'users:logout' %}" method="post">
              {% csrf_token %}
              <button class="btn btn-link fs-5" type="submit">Log out</button>
            </form>
            {% else %}
            <li class="nav-item">
              <a class='nav-link fs-5' href="{% url 'users:register' %}">Register</a> 
            </li>
            <li class="nav-item">
              <a class='nav-link fs-5' href="{% url 'users:login' %}">Log in</a>
            </li>
            {% endif %}
          </ul>
        </div> 
      </div>
    </nav>
  <main role="main" class='container p-4'>    
    <div class='pb-2'>
      {% comment %} mb-2 border-bottom {% endcomment %}
      {% block page_header %} {% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

  <footer role="footer" class='bg-success mt-4 p-5 text-white'>
    <div class="row">
      <div class=" col-sm-6 d-none d-lg-block">
        <div class="d-flex flex-column justify-content-between">
          <img class="mb-3" width='75px' src="{% static 'learning_logs/images/logo.png' %}" alt="my Logo" />
          <p class="mt-5">&copy; 2025. All rights reserved.</p>
        </div>
      </div>
    <div class="col-sm-3 mt-4">
      <ul class="nav text-white d-flex flex-column align-items-center">
        <li class="nav-item">
          <a class="nav-link active navbar-brand text-uppercase fs-4" href="{% url 'learning_logs:index' %}" aria-current="page">EduTrack </a>
        </li>
        <li class="nav-item">
          <a class='text-white nav-link fs-5' href="{% url 'users:register' %}">Register</a> 
        </li>
        <li class="nav-item">
          <a class='text-white nav-link fs-5' href="{% url 'users:login' %}">Log in</a>
        </li>
        <li class="nav-item">
          <a class="text-white nav-link fs-5" aria-current="page" href="{% url 'learning_logs:topics' %}">Topics</a>
        </li>
      </ul>
    </div>
    <div class="col-sm-3 mt-4">
      <ul class="nav flex-column align-items-center text-white">
        <li class="nav-item">
          <a class="nav-link active navbar-brand text-uppercase fs-4" href="{% url 'learning_logs:index' %}" aria-current="page">Home</a>
        </li>
        <li class="nav-item">
          <a class="text-white nav-link fs-5" aria-current="page" href="{% url 'learning_logs:index' %}#Qoutes">Qoutes</a>
        </li>
        <li class="nav-item">
          <a class='text-white nav-link fs-5' href="{% url 'learning_logs:index' %}#About">About us</a> 
        </li>
        <li class="nav-item">
          <a class='text-white nav-link fs-5' href="{% url 'learning_logs:index' %}#Features">Features</a>
        </li>
        
      </ul>
      <div class="d-flex justify-content-center">
        <p class="mt-4 d-lg-none d-sm-block ">&copy; 2025. All rights reserved.</p>
      </div>
    </div>
    </div>
    
  </footer>

  <!-- Bootstrap JS Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %} 
{% load django_bootstrap5 %}

{% block page_header %}
  
  <div class="w-50 p3 mx-auto">
    <h2>Edit entry:</h2>
  </div>

{% endblock page_header %}

{% block content %} 

<div class="w-50 p3 mx-auto">

  <h3><a href"{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>

  <form class='form' method="post" action="{% url 'learning_logs:edit_entry' entry.id %}">
    {% csrf_token %} 
    {% bootstrap_form form %} 
    {% block buttons %}
        <button class='btn btn-primary fs-5' name="submit">Save changes</button>
      {% endblock buttons %}
  </form>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %} 
{% load static %}

{% block page_header %}
  <div class="row align-items-center justify-content-center" id="About">
    <div class='col-lg-7 col-sm-12 p-4'>
      <span class='fs-4'>Track everything you learn</span>
      <h1 class='display-3 animate__animated animate__backInLeft animate__slow'>Master Your Learning Journey</h1>

      <p class='lead'> EduTrack empowers students and professionals to stay focused and retain knowledge by making it easy to log 
        topics and add learning notes along the way. Register, start a topic, and build your learning archive effortlessly.
        </p>
      <a class='btn btn-lg btn-primary animate__animated animate__pulse animate__infinite' href="{% url 'users:register' %}" role='button'>Join EduTrack Today &raquo;</a>
    </div>
    <div class="col-lg-5 col-sm-10">
      <img width='100%' src="{% static 'learning_logs/images/logo.png' %}" alt="Hero image" />
    </div>
  </div>
{% endblock page_header %}

{% block content %}

<div id="textCarousel" class="carousel slide bg-success-subtle mt-4" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#textCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#textCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#textCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#textCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>
    <button type="button" data-bs-target="#textCarousel" data-bs-slide-to="4" aria-label="Slide 5"></button>
    <button type="button" data-bs-target="#textCarousel" data-bs-slide-to="5" aria-label="Slide 6"></button>
  </div>
  <div class="carousel-inner text-center p-4" id="Qoutes">
    <div class="carousel-item active">
      <div class="card">
        <div class="card-header">
          Inspirational Quote
        </div>
        <div class="card-body">
          <figure>
            <blockquote class="blockquote">
              <p class="fs-4 fst-italic">"Don’t just learn—track your growth, reflect, and thrive."</p>
            </blockquote>
            <figcaption class="blockquote-footer">
               EduTrack 
              {% comment %} <cite title="Source Title">Source Title</cite> {% endcomment %}
            </figcaption>
          </figure>
        </div>
      </div>
        {% comment %} <p class="fs-4 fst-italic">"Don’t just learn—track your growth, reflect, and thrive." <br>— EduTrack</p> {% endcomment %}
    </div>
    <div class="carousel-item">
      <div class="card">
        <div class="card-header">
          Inspirational Quote
        </div>
        <div class="card-body">
          <figure>
            <blockquote class="blockquote">
              <p class="fs-4 fst-italic">"An investment in knowledge pays the best interest."</p>
            </blockquote>
            <figcaption class="blockquote-footer">
               Benjamin Franklin
            </figcaption>
          </figure>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card">
        <div class="card-header">
          Inspirational Quote
        </div>
        <div class="card-body">
          <figure>
            <blockquote class="blockquote">
              <p class="fs-4 fst-italic">"Every expert was once a beginner."</p>
            </blockquote>
            <figcaption class="blockquote-footer">
               Helen Hayes
            </figcaption>
          </figure>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card">
        <div class="card-header">
          Inspirational Quote
        </div>
        <div class="card-body">
          <figure>
            <blockquote class="blockquote">
              <p class="fs-4 fst-italic">"Learning never exhausts the mind."</p>
            </blockquote>
            <figcaption class="blockquote-footer">
               Leonardo da Vinci
            </figcaption>
          </figure>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card">
        <div class="card-header">
          Inspirational Quote
        </div>
        <div class="card-body">
          <figure>
            <blockquote class="blockquote">
              <p class="fs-4 fst-italic">"Success is the sum of small efforts, repeated day in and day out."</p>
            </blockquote>
            <figcaption class="blockquote-footer">
               Robert Collier
            </figcaption>
          </figure>
        </div>
      </div>  
    </div>
    <div class="carousel-item">
      <div class="card">
        <div class="card-header">
          Inspirational Quote
        </div>
        <div class="card-body">
          <figure>
            <blockquote class="blockquote">
              <p class="fs-4 fst-italic">"Live as if you were to die tomorrow. Learn as if you were to live forever."</p>
            </blockquote>
            <figcaption class="blockquote-footer">
               Mahatma Gandhi
            </figcaption>
          </figure>
        </div>
      </div>  
    </div>
  </div>
</div>

  <button class="carousel-control-prev" type="button" data-bs-target="#textCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#textCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

  <div id="textCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="5000"></div>
</div>

<div class="mt-5" id='Features'>
  <h2>How to Use EduTrack</h2>
  <div class="row">
    <div class="col-lg-5 mt-3">
      <div class="card">
        <h5 class="card-header">Create an Account</h5>
        <div class="card-body">
          <h5 class="card-title">icon</h5>
          <p class="card-text">Register a free account to start your learning journey. Start your success story today.</p>
          <a href="{% url 'users:register' %}" class="btn btn-primary">Register</a>
        </div>
      </div>
    </div>
    <div class="col-lg-5 ms-auto mt-4">
      <div class="card">
        <h5 class="card-header">Add a New Topic</h5>
        <div class="card-body">
          <h5 class="card-title">icon</h5>
          <p class="card-text">Click "Add Topic", give it a meaningful name, and begin organizing what you want to learn.</p>
          <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">Add a New Topic</a>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-5 mt-4">
      <div class="card">
        <h5 class="card-header">Manage your Topics</h5>
          <div class="card-body">
          <h5 class="card-title">icon</h5>
          <p class="card-text">Edit or delete topics anytime. Keep your learning space organized and relevant to your current focus.</p>
          </div>
        </div>
    </div>
    <div class="col-lg-5 ms-auto mt-4">
      <div class="card">
        <h5 class="card-header">Add Rich Learning Entries</h5>
          <div class="card-body">
          <h5 class="card-title">icon</h5>
          <p class="card-text">Inside a topic, click "Add Entry". Write down what you’ve learned.</p>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-5 mt-4">
      <div class="card">
        <h5 class="card-header"> View and Reflect on Entries </h5>
          <div class="card-body">
          <h5 class="card-title">icon</h5>
          <p class="card-text"> Entries are displayed with their date and time, helping you track your learning progress like a digital journal. </p>
          </div>
      </div>

    </div>
    <div class="col-lg-5 ms-auto mt-4">
      <div class="card">
        <h5 class="card-header"> Mobile-Friendly Access </h5>
          <div class="card-body">
          <h5 class="card-title">icon</h5>
          <p class="card-text"> Use EduTrack seamlessly on your phone, tablet, or computer. Keep learning wherever you are. </p>
          </div>
        </div>
    </div>
  </div>
</div>

<div class="row align-items-center mt-4 p-4 bg-success-subtle">
  <div class="col-lg-7">
    <img style="width:100%; height: 200px; object-fit:cover" src="{% static 'learning_logs/images/logo.png' %}" alt="my Logo" />
  </div>
  <div class="col-lg-5">
    <figure>
      <blockquote class="blockquote">
        <p class="fs-4 fst-italic">"Success is the sum of small efforts, repeated day in and day out."</p>
      </blockquote>
      <figcaption class="blockquote-footer">
          Robert Collier
      </figcaption>
    </figure>
      <a class='btn btn-lg btn-primary animate__animated animate__pulse animate__infinite' href="{% url 'users:register' %}" role='button'>Join EduTrack Today &raquo;</a>
  </div>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %} 
{% load django_bootstrap5 %}

{% block page_header %}
  
  <div class="w-50 p3 mx-auto">
    <h2>Add a new entry:</h2>
  </div>

{% endblock page_header %}

{% block content %} 

<div class="w-50 p3 mx-auto">
  <h3><a href"{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>

    <form class='form' action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
      {% csrf_token %} 
      {% bootstrap_form form %} 
      {% block buttons %}
        <button class='btn btn-primary fs-5' name="submit">Add entry</button>
      {% endblock buttons %}
    </form>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %} 
{% load django_bootstrap5 %}

{% block page_header %}
  
  <div class="w-50 p3 mx-auto">
    <h2>Add a new topic:</h2>
  </div>

  {% endblock page_header %}

{% block content %}

<div class="w-50 p3 mx-auto">
  <form class='form' action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %} 
    {% bootstrap_form form %} 
    {% block buttons %}
      <button class='btn btn-primary fs-5' name="submit">Add Topic</button>
    {% endblock buttons %}
    </form>
  </div>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %} 

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a type="button" class="btn btn-primary fs-5" href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>


  {% for entry in entries %}
    <div class='card mb-3'>
      <h5 class='card-header'> 
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a class="ms-4 text-decoration-none" href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
        </smnall>
      </h5>

      <div class='card_body fs-6 p-3'>
        {{ entry.text|linebreaks }}
      </div>
    </div>
  
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %} 


{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <h3><a class='text-decoration-none text-body-emphasis' href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a></h3>
      </li>
    {% empty %}
      <li>
        <h3>No topics have been added yet.</h3>
      </li>
    {% endfor %}
  </ul>

<h3><a type="button" class="btn btn-primary fs-4" href="{% url 'learning_logs:new_topic' %}">Add a new topic</a><h3>

{% endblock content %}